### ISSUE TITLE
Decrypting Data from a WD My Book Studio 1TB

### ISSUE THREAD

**Issue by robmorgan** [andlabs/reallymine#110]
Hi everyone,

I have a WD SATA hard-drive I extracted from a My Book Studio about 7 years ago (Model Number: _WDBAAJ0010HSL-AESN_). I dropped the enclosure before moving cities and figured I'd most likely killed the hard drive. After sitting on this for several years I finally took the drive to a data recovery expert to see if he could extract anything. It turns out as I've read on here and the @themaddoctor 's repos that the disk itself was okay, just encrypted. However, unless anyone can tell me otherwise I think I'm in the unfortunate bucket where the keyblock is located in the enclosure itself. I believe I may have had a PLX chipset. So far I've tried following the PDF guides and using `reallymine` with no success. It just runs for days on end. I'm posting here in case anyone can help, but also maybe my specific model and data could be useful for others.

I've grepped over the drive data searching for a `WD` magic string and the SMART Drive Dump, without any success. You can find the HD modules attached here.

[wd-hd-modules.zip](https://github.com/andlabs/reallymine/files/5014963/wd-hd-modules.zip)

I guess my only other options are to try and brute force the encryption for the next 10-20 years... or hope to buy a 2nd hand enclosure on eBay? 

Cheers,

Rob

**Comment by themaddoctor** [comment]
Here are some thoughts/findings:

I did not find anything in the modules that looks like a keyblock.

You didn't say, but have you thrown away the enclosure?

No one has ever asked about a PLX-chipped 1TB drive before (that I can remember). Only 3TB drives. That doesn't
mean that they don't exist.

There might be a good chance that the key was stored in an EPROM on the bridge card, which is bad news if you
threw it away.

Can you post a hexdump of the first sector (sector 0) and the manufacture date from the disk label? There is a very very
very very very very small chance it can help. I use a lot of "very"s because I don't want you to get hopeful.

**Comment by robmorgan** [comment]
> I did not find anything in the modules that looks like a keyblock.

Roger!

> You didn't say, but have you thrown away the enclosure?

Yeah sorry, I forgot to mention the key detail. I threw away the enclosure about ~7 years ago!

> No one has ever asked about a PLX-chipped 1TB drive before (that I can remember). Only 3TB drives. That doesn't
mean that they don't exist.

That sounds about right. I've read a ton of the material on the internet and the existing methods for other chips didn't seem to work.

> There might be a good chance that the key was stored in an EPROM on the bridge card, which is bad news if you
threw it away.

Great! ;)

> Can you post a hexdump of the first sector (sector 0) ?

Let me know if this helps:

```
❯ sudo dd if=/dev/disk2 skip=0 count=1 | hexdump -C
1+0 records in
1+0 records out
00000000  a2 41 39 99 04 77 53 63  ea 50 e1 6f bf ab 87 94  |.A9..wSc.P.o....|
512 bytes transferred in 0.000373 secs (1373071 bytes/sec)
00000010  e7 ad e5 d4 42 b3 51 55  a6 38 e4 a5 3c d9 cb e2  |....B.QU.8..<...|
*
00000200
```

Note: I ran this on a Mac using a 1:1 backup clone, so let me know if I should fire up Linux on the original disk. Here's a photo of the original disk:

![IMG_7335](https://user-images.githubusercontent.com/178939/89195002-6beae680-d5a8-11ea-9bc5-2feae842ef1a.jpg)

**Comment by themaddoctor** [comment]
I'm out of ideas. Sorry.

**Comment by themaddoctor** [comment]
I'm out of ideas. Sorry.

**Comment by robmorgan** [comment]
@themaddoctor ok thanks for taking a look. I'll close this issue in a few days and re-open if I have any further luck 👍
