### ISSUE TITLE
How long does reallymine getdek need to complete?

### ISSUE THREAD

**Issue by pillepalle1** [andlabs/reallymine#130]
I am running 

```
sudo reallymine getdek /dev/sdb
```

as indicated in [the Readme](https://github.com/andlabs/reallymine#getting-the-decryption-key) but the operation is now running for several hours.

The drive is 5.45 TB and one of two (what WD calls) RAID 1 mirrored drives. Does `reallymine` need to make a pass over the whole drive to find the key? I am growing a bit suspicious as I would expect this to take no more than a few seconds.

**Comment by themaddoctor** [comment]
You have one of the chips that no one understands yet. Look on the SATA-USB bridge card. Is there a JMS561 chip on it?

**Comment by pillepalle1** [comment]
Sure enough ![image](https://user-images.githubusercontent.com/30006468/149873074-37ee5a98-b1e7-4e48-9a12-2af9144a0ddb.jpeg)

**Comment by themaddoctor** [comment]
Please read issue #129. Sorry, but there is nothing that can be done until you find the keyblock.

**Comment by pillepalle1** [comment]
This is a nightmare. 

Ok, I will see if I can get hddsupertools to run on my Arch machine and continue the discusssion in the other issue.
