### ISSUE TITLE
Question about drive with password

### ISSUE THREAD

**Issue by PatrickL546** [andlabs/reallymine#131]
I have a wdbmwv0020bbk-05
![image](https://user-images.githubusercontent.com/75874561/156942331-9d7055b0-c424-4704-b90e-47dd471bf646.png)
Can this be used to 'unlock' it?
If not, is there a brute force program to unlock it?
I have the old password and I just added a couple of characters so It shouldn't take long to crack it.

**Comment by themaddoctor** [comment]
Only if you can disable the encryption chip on the controller board and read the raw data from the drive.
There are many different configurations for Passport drives, so you will need to google until you find a how-to that matches yours.
The process will involve removing some of the connections on the controller board.
I have not done this myself, so I can't be much more help.

If you succeed in bypassing the encryption chip, DO NOT plug the drive into a Windows computer. You will need linux.

**Comment by PatrickL546** [comment]
Ok, thanks for info
