### ISSUE TITLE
How do I know what bridge probably is used by my passport

### ISSUE THREAD

**Issue by junzhli** [andlabs/reallymine#141]
Hello! Is there anyone who knows how to recognize the bridge is used by my passport? I am wondering if my passport is vulnerable to this way of decryption without user-specified password?
Btw, those vulnerable chips are still used in recent wd products?
Thanks!

**Comment by themaddoctor** [comment]
You might try reading the numbers on the chips.

**Comment by junzhli** [comment]
Do I need to open my passport to see that chip inside?

**Comment by themaddoctor** [comment]
Guess so.

**Comment by junzhli** [comment]
Thanks! I'll leave it intact and assume it's vulnerable to this attack surface by considering software-based encryption solution to protect data. As I am afraid that I can't get everything back after I opened this lol
