### ISSUE TITLE
undefined io.seekend issue

### ISSUE THREAD

**Issue by silkyclouds** [andlabs/reallymine#19]
Hi guys,

I try to get reallymine to work but do encounter several issues. 

Running it under ubuntu linux I get this error message after the go get github.com/andlabs/reallymine command : 

#github.com/andlabs/reallymine/disk go/src/github.com/andlabs/reallymine/disk/disk.go 27: undefined: io.SeekEnd

Therefore I can not run it for now. 

I installed it successfully under windows (which would be my first choice as my hdd is ntfs formated and I don't have to make use of a VM to run it!) but I can't figure out the correct syntax to tell reallymine to decrypt my disk. 

Disk is listed as disk3 in diskpart tool (disque 3 -> in French) 

Could a nice guy around here tell me how to decrypt the content of my disk to another external hdd without creating an image? I'd just like to decrypt and copy all the files just like they used to be on the encrypted drive to another same size hdd plugged trough usb. 

What is the right syntax to use ? 

And by the way, are you guys hangin somewhere on irc ?

thanks !

**Comment by silkyclouds** [comment]
Hello again,

to list the drives I opened a command prompt and entered the following command : 

wmic diskdrive list brief 

Then, I did run the getdek command but got an access denied message. 

Solution is simply to open the prompt using administrative right, and run the command again. 

So now reallymine is running BUT I still get an error when trying to run it. 

reallymine getdek \\.\PHYSICALDRIVEX returns me the following error:

error running getdek seek \\.\PHYSICALDRIVE3  incorrect function (fonction incorrecte -> because my OS speaks French). 

Any idea how to solve this ?

**Comment by andlabs** [comment]
The first issue is a Go version issue. I'll have to figure out what to do about it.

There is an issue already open for the second issue... I forget the number right now.

**Comment by silkyclouds** [comment]
Hi andlabs and thank you for answering ! 

Well, as you may have read, I finally was able to list drives and get rid of the access denied error message by using reallymine under windows. 

But now I have that message in return of the "reallymine getdek \.\PHYSICALDRIVEX" command : 

error running getdek seek \.\PHYSICALDRIVE3 fonction incorrecte

any clue what it could be ?

**Comment by silkyclouds** [comment]
OK so I just did read the other issue opened by a windows user. It looks like reallymine will not work under Windows right ? 

So now I do have that VM running linux, but then I need to know what to do to fix this #github.com/andlabs/reallymine/disk go/src/github.com/andlabs/reallymine/disk/disk.go 27: undefined: io.SeekEnd 

this is happening after I enter the go get command. Any way to fix this ?
