### ISSUE TITLE
can't get reallymint to run on linux

### ISSUE THREAD

**Issue by themaddoctor** [andlabs/reallymine#24]
reallymine-release1 > go run main.go
# command-line-arguments
./main.go:33: undefined: SectorSize
./main.go:33: const initializer NumSectorsAtATime * SectorSize is not a constant
./main.go:58: undefined: FindKeySectorAndBridge
./main.go:73: undefined: TryGetDecrypter
./main.go:108: undefined: SectorSize
./main.go:111: undefined: DecryptNext
./main.go:124: undefined: FindKeySectorAndBridge
./main.go:131: undefined: TryGetDecrypter
./main.go:150: undefined: SectorSize
./main.go:151: undefined: DecryptNext
./main.go:151: too many errors

reallymine-master > go run main.go
# command-line-arguments
./main.go:33: undefined: SectorSize
./main.go:33: const initializer NumSectorsAtATime * SectorSize is not a constant
./main.go:58: undefined: FindKeySectorAndBridge
./main.go:73: undefined: TryGetDecrypter
./main.go:108: undefined: SectorSize
./main.go:111: undefined: DecryptNext
./main.go:124: undefined: FindKeySectorAndBridge
./main.go:131: undefined: TryGetDecrypter
./main.go:150: undefined: SectorSize
./main.go:151: undefined: DecryptNext
./main.go:151: too many errors

**Comment by andlabs** [comment]
You cannot run this using `go run`. Use `go build` instead.

**Comment by themaddoctor** [comment]
Never mind. Sorry. I see that this was in one of the closed issues.
