### ISSUE TITLE
Not able to start main.go -->

### ISSUE THREAD

**Issue by LuckyLuzz** [andlabs/reallymine#3]
Hey, 
I am new with "go" so I may do something wrong, but the Terminal give's me errors when starting the main.go

go run /home/Downloads/reallymine-master/main.go
(#) command-line-arguments
Downloads/reallymine-master/main.go:33: undefined: SectorSize
Downloads/reallymine-master/main.go:33: const initializer NumSectorsAtATime * SectorSize is not a constant
Downloads/reallymine-master/main.go:58: undefined: FindKeySectorAndBridge
Downloads/reallymine-master/main.go:73: undefined: TryGetDecrypter
Downloads/reallymine-master/main.go:108: undefined: SectorSize
Downloads/reallymine-master/main.go:111: undefined: DecryptNext
Downloads/reallymine-master/main.go:124: undefined: FindKeySectorAndBridge
Downloads/reallymine-master/main.go:131: undefined: TryGetDecrypter
Downloads/reallymine-master/main.go:150: undefined: SectorSize
Downloads/reallymine-master/main.go:151: undefined: DecryptNext
Downloads/reallymine-master/main.go:151: too many errors

Would be awesome if you could help! Thank :)

**Comment by andlabs** [comment]
I have not updated this project in ages; it reflects a now-ancient version of package ui.

**Comment by andlabs** [comment]
You can't run only main.go. You have to build the complete binary with all the .go files.

**Comment by LuckyLuzz** [comment]
thanks for reply! Got it running with LiteIDE for Ubuntu. Had to download another libary and copy it to src\github.com\mendsley\gojwe.... Then I startet it over Terminal. 
$ ./reallymine-master /dev/sda /dev/sda5/WDfile.img
With my first 500GB WD (encrypted) it appears a error ("error opening encrypted file ") input/output error   and with the second Harddrive a 1TB WD (Not encrypted) it was "Finding Sector " the whole night.

go build is not working. Same error as with go run. I guess that's because of the not included gojwe Lib. 

Yeah but unforgently it was not working at all :(         How can I see if the chip from my Harddrive is supported?

**Comment by andlabs** [comment]
Is the 500GB drive damaged?

Can you extract the last 100 or so MB of the 1TB drive?

**Comment by LuckyLuzz** [comment]
Both drives are fine. I could't find the WD.img file. I tried it also with the reallymine-linux-amd64.bin file with command:

./reallymine-linux-amd64 /dev/sdd /dev/sda5/WD1.img
bash: ./reallymine-linux-amd64: Permission denied

sudo ./reallymine-linux-amd64 /dev/sdd /dev/sda5/WD1.img
sudo: ./reallymine-linux-amd64: command not found

not working either.

Would be pretty good if you could write a instruction or have a ready debug file to download for Ubuntu 16.04 LTS ;)

Thanks again!

**Comment by andlabs** [comment]
You need to mark the download as executable:
```
chmod a+x reallymine-linux-amd64
```

**Comment by MrDecay** [comment]
Just to clarify "reallymine" is for westerndigital drives that have the
hardware based encryption.  Usually on the USB adapter for 3.5  or on the
USB circuit board for 2.5.
Once we remove/bypass  the encryption/USB controller.  We can access the
encrypted data sectors. At this point we have can use really mine to
decrypt to a decrypted image.
So in re cap.
If your drive has bad sectors. It would fail since reallymine doesn't do
data recovery.
If the drive is not encrypted with the western digital hardware based
default encryption . it will not work.

So lets start with your 500gig.
Do you have the model number. So I can check around see if I can get the
info from which USB controller its using. ?

**Comment by LuckyLuzz** [comment]
Ok understood. I haven't checks the Harddrive bad sectors. Since it was running befor normally. Just the password got lost.
P/N: WDBACY5000ARD-01
S/N: WXG1A51L7908
R/N: C4B

I marked it and it's now showing the same error as the debuged file.
sudo ./reallymine-linux-amd64 /dev/sdb dev/sda5/WDfile.img
Finding key sector...
[BUG] error reading sector in FindKeySectorAndBridge(): read /dev/sdb: input/output error
Please report to andlabs on github.com/andlabs/reallymine.

So now I should run ddrescue I guess...

**Comment by MrDecay** [comment]
So it sounds like you lost the smartware pass word.?

**Comment by LuckyLuzz** [comment]
yes, my girlfriend did... We had a couple try's but with Smartware we have to disconnect after every 3 try's.  So I googled, ended up here and hopefully we can somehow recover her files. Otherwise I am just loseing a couple hours having fun with Linux I though.

**Comment by MrDecay** [comment]
Ahhh .  hmmm. Well really mine is for wdc hardware encryption based off the
USB chip. I'm not sure on the implementation for smartware.   Lets see what
Pietro says. In the meantime sit tight. If the drives are not damaged .
then lets not break them :)   so only the 500gb lost the smartware pass
word and the 1tb was more of let me see if it works?

**Comment by andlabs** [comment]
Whether or not the password is necessary depends on the type of encryption used.

It is possible that the 1TB drive uses PLX/Oxford Semiconductor chips, which I still don't have support for, mainly because I don't have samples to test with.

**Comment by LuckyLuzz** [comment]
Right, on the 1tb is actually no password at all. Just wane see if it works and creates a img. So lets concentrate on the 500Gb Drive :)

**Comment by LuckyLuzz** [comment]
I have was hoping that at least I could go around the "You have to disconnect after 3 try's" so I may could try a couple passwords in a row. I'm close to the right pw, I can feel it :D

**Comment by LuckyLuzz** [comment]
The Harddrive had 1 Bad Sector. ddrescue has worked 48h and did not write one MB in a image file.. I give it up. Thanks anyway for help!!

**Comment by andlabs** [comment]
If it couldn't recover 1MB you should still be able to decrypt the incomplete image.

**Comment by LuckyLuzz** [comment]
hmm I don't understand. ddrescue has not created a file at all, there was no output. It has just counted a number in the Terminal 0-XXXXXXXXXXXXXXXXX in 48h. That's it. I need a tutorial or somethink.


Where can I sent the harddrive to?

**Comment by andlabs** [comment]
What command did you use?

**Comment by LuckyLuzz** [comment]
I had downloaded a GUI over the Ubuntu SoftwereCentre. Then I chose Input drive, Output file dir and started it. 

Do you see it Master? There is your chance to have me as your ( stupid linux newby) student ^^



Where can I sent the Drive to? :dancers:

**Comment by MrDecay** [comment]
Sounds like he wasn't able to pull any sectors.  Only recommendation if
your in the states try myharddrivedied see if they can recover from
smartware passwords. Any where else outside the u.s.  I have no experience
