### ISSUE TITLE
decrypted.img going beyond source Disk size ???

### ISSUE THREAD

**Issue by keller212** [andlabs/reallymine#36]
I have been decrypting a 1tb WD for the last 7 Days.
I thought it would have finished at 931.5 gb
But it is still decrypting. the decrypted.img file has gone to 938.5 gb & still going....

Any advice ???

**Comment by keller212** [comment]
I think i found my answer.
Ubuntu shows file size in GBits not GBytes.

**Comment by keller212** [comment]
951GB & still going.

**Comment by keller212** [comment]
at this stage, should i stop the decryption process & try to recover files from the image ???

**Comment by MrDecay** [comment]
Did it finished gracfully

**Comment by keller212** [comment]
Yes it did. it finished at 1tb

**Comment by andlabs** [comment]
The drive has a 300MB or so unencrypted space at the end reserved for WD's utility software. The USB bridge transparently splits the disk into two, but when using reallymine you're assumed to be bypassing the bridge, so you get access to the whole drive.

**Comment by athomic1** [comment]
If I remember right, that utility space is basically a CD/DVD image. I was wondering if there's some way to detect the beginning of that section, so it could possibly be extracted as an ISO file?

**Comment by andlabs** [comment]
It could probably be done by looking for some filesystem or storage format identifier.

If not, some of the DEK blocks have the fake disk size in their headers, and all of them do in the service area (that require special vendor-specific ATA commands to access).
