### ISSUE TITLE
Finally decrypted drive, but drive still unmountable... solutions?

### ISSUE THREAD

**Issue by J188** [andlabs/reallymine#59]
Managed to finally decrypt a WD drive using this sweet program, unfortunately for whatever reason the .img file is still not mountable.  Is there any other steps that I need to do in order to make sure that I can mount it? Or did something go wrong/ incompatible?

Steps I took:

1. Created Rescued image file using DDRescue (Note no bad sectors or issues related to the drive upon success)
2. Ran 'decrypt' on the image file, waited nearly a week.
3. Process completed, no error messages.
4. Attempted to mount with DiskImageMounter on MacOS; unrecognizable. ("No mountable file systems")

Any solutions? Serious troubleshooting here... thought I had finally come to an end with the impossible access to the drive!  Thank you!

**Comment by themaddoctor** [comment]
I can only help if you use linux or mac. There are others who can help you with windows.

**Comment by J188** [comment]
I am using a mac with this

**Comment by themaddoctor** [comment]
Was the disk formatted for NTFS or HFS+?

Dump the first 2MB for me to look at (replace diskX with the right one):
sudo dd if=/dev/diskX count=4096 of=start.bin

**Comment by J188** [comment]
The actual disk was an NTFS format, I am certain.  I created the .bin file but I can't dump it here... how do I go about getting that to you ?  You wanted the file from the original drive or the decrypted version?

**Comment by J188** [comment]
Nevermind, solved that.  Here is the file.  Note that it is from the actual drive that I am trying to decrypt, not the decrypted image.  Assuming that was the one you wanted.

https://filebin.ca/3me2K54QS4hF/start.bin

Thanks in advance!

**Comment by andlabs** [comment]
This is a full disk image; you can't just mount it as-is. First, you'll need to fool OS X into thinking the image is a drive itself. This is coverred in various places on the Internet, but the gist is

```
$ hdiutil attach -imagekey diskimage-class=CRawDiskImage -nomount rawimage
(hdiutil will print the resultant /dev/diskN for the image)
$ ls ﻿﻿﻿/dev/diskNs* # find out what the partitions are
$ # do work
$ hdiutil detach /dev/diskN # when done; make sure you unmount everything first
```

**Comment by J188** [comment]
@andlabs ok so speaking on the final decrypted image, I am to just go about what you've shown above? 

You noted to ensure to unmount everything first... the image file that I have is not on the OS X drive but on an external one.  Is this fine?

I will try to do what you've wrote above and hopefully that fixes this so I can access the drive, finally

**Comment by J188** [comment]
also, novice question, but for that first command line where do I input the image file if it is called Decrypted.img?  executing from the same directory as where the file is within.

**Comment by themaddoctor** [comment]
One big problem you have is that the drive was repartitioned before decrypting. The dump that you sent me has a (not encrypted) GPT partition table on it. I also has zeroes up until byte 0x7e00.

**Comment by J188** [comment]
Device Identifier:        disk4
   Device Node:              /dev/disk4
   Whole:                    Yes
   Part of Whole:            disk4
   Device / Media Name:      Disk Image

   Volume Name:              Not applicable (no file system)
   Mounted:                  Not applicable (no file system)
   File System:              None

   Content (IOContent):      None
   OS Can Be Installed:      No
   Media Type:               Generic
   Protocol:                 Disk Image
   SMART Status:             Not Supported

   Disk Size:                1.5 TB (1500301910016 Bytes) (exactly 2930277168 512-Byte-Units)
   Device Block Size:        512 Bytes

**Comment by J188** [comment]
@themaddoctor That doesn't sound good at all.... I had ran the decrypt on numerous occasions unsuccessfully before I was finally able to make the final image.  Noting also that most of the initial attempts of me trying to learn how to figure it out was done on the actual drive and not a rescued image until I had come across that idea later.  

That being said, the likelihood of recovering anything on my drive?

**Comment by themaddoctor** [comment]
I dunno. Try dumping the first 2MB from the decryted image for comparison

**Comment by J188** [comment]
Try this? https://filebin.ca/3meSMYnfLLpX/start2.bin

**Comment by J188** [comment]
@andlabs I guised the mount via your first command and the only way to mount the disk image was by this: (Note any other commands were not mounting once it was listed on diskutil)
`$ diskutil mountDisk /dev/disk4`

nothing otherwise shows... perhaps there is an issue with the drive previous to the decryption? otherwise I should be able to read it properly by this point?

**Comment by themaddoctor** [comment]
There appears to be an NTFS filesystem at byte 0x7e00

**Comment by themaddoctor** [comment]
Top 100 trance and techno songs of all time

**Comment by themaddoctor** [comment]
You could set up a loop device that starts at byte 0x7e00 and mount that, but I only know how to do it in linux.

**Comment by J188** [comment]
@themaddoctor that makes sense to me (NTFS).  Any suggestions on how I can properly mount this or is it fouled up because it may be reading multiple filesystems?

**Comment by J188** [comment]
@themaddoctor so basically I could be in luck assuming I am able to figure out how to do that... at least a better chance than nothing?

**Comment by themaddoctor** [comment]
I only know how to do it in linux.

**Comment by themaddoctor** [comment]
Sure. I recovered a jpeg from the sample you sent. Top 100 trance and techno songs of all time

**Comment by J188** [comment]
Ha! Of all things...there is hope yet.  Though the luck is dwindling... now just have to figure out how to do it on OS X and hope for the best.   That's why you said that

**Comment by themaddoctor** [comment]
Without loop devices, you could make *another* image, that starts at byte 0x7e00.
Like this:
dd if=oldimage skip=63 bs=512 of=newimage

Then mount it like andlabs said.

**Comment by J188** [comment]
Well, I can't seem to figure out how to do the loop as of now so this may be the best option that I have right now.  I can give this a shot and hope that this works.  Just a lot more time burning on the file making alone is killing me.  I will try this and see where this goes.

**Comment by andlabs** [comment]
Hi, please see my code snippet above, because I just told you how to do that on OS X

**Comment by themaddoctor** [comment]
@andlabs Problem with the snippet is that the partition table was corrupted. It is visible in the encrypted drive, and scrambled in the decrypted image.

**Comment by andlabs** [comment]
Huh, I didn't notice that in the link posted. Sorry for the tone, if any!

**Comment by J188** [comment]
So turns out that after re-creating that new file based on @themaddoctor 's suggestion, everything works! I can access it no problem and easily mounts as if it were a drive itself.  

Thanks a whole lot for the support and the program itself to the both of you!  Glad I can finally get inside the drive!
