### ISSUE TITLE
need help with 1TB WD My Book Essentials

### ISSUE THREAD

**Issue by blonkm** [andlabs/reallymine#68]
I am pretty far in the process, but now I am stuck. This concerns a WD Book Essential 1TB that I have taken out of the enclosure and hooked up to a Lubuntu with a SATA cable. The board chip says Symwave SW6316.

I do have some linux experience, and I'm a programmer. But this is beyond my skills.

    ciencia@ciencia-HP-Pro-3000-Microtower-PC:~$ lsblk
    NAME   MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
    loop0    7:0    0 931,5G  0 loop 
    sda      8:0    0 149,1G  0 disk 
    ├─sda1   8:1    0   100M  0 part 
    ├─sda2   8:2    0 120,5G  0 part 
    ├─sda3   8:3    0     1K  0 part 
    └─sda5   8:5    0  28,5G  0 part  /
    sdb      8:16   0 931,5G  0 disk 
    └─wd   253:0    0 931,5G  0 crypt

I can see the /sdb/wd as being a 'crypt', but I'd like to access files. I am not sure how to see if I have to apply a password and how. Nobody here remembers if they initially set a password. If they did it's most likely something simple, like 'admin' or blank.

    $reallymine getdek /dev/sdb
        bridge type Symwave
        DEK: 766FF121EF6E9034C99FF985A7BAAE7C3B273E4DA343D4102407BF5A8AAB3E8A
        decryption steps: decrypt

I read the PDF from [here](https://github.com/themaddoctor/linux-mybook-tools/blob/master/Mounting%20encrypted%20WD%20disks%20in%20linux.pdf), but don't know what to do now.

If I try to use reallymine decryptsector it never asks for a password.

Unfortunately I don't have a large disk to make an image which is why I am looking for ways to access the files directly.

When I use decrypt for the full drive it seems to keep growing, much larger than the drive itself. Should I let it continue??

```
$fdisk -l 
[..]
Disk /dev/sdb: 931,5 GiB, 1000204886016 bytes, 1953525168 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x8c3ca73f


Disk /dev/mapper/wd: 931,5 GiB, 1000204886016 bytes, 1953525168 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
```

Ready to provide any details.

**Comment by themaddoctor** [comment]
You said:
"I read the PDF from here, but don't know what to do now."

What steps have you already followed?

**Comment by blonkm** [comment]
everthing including
`sudo file -sL /dev/mapper/wd`
but then I don't see 
`/dev/mapper/wd: DOS/MBR boot sector …`
but
`/dev/mapper/wd: data`

I didn't get any errors in the process towards this.
`reallymine getdek ` returns the same DEK as the manual process

Is it OK to rebuild a MBR and partition table using e.g. fdisk, testdisk or gparted (it was originally NTFS on Windows) or would that somehow destroy data?

**Comment by themaddoctor** [comment]
p.s. You said you don't remember if there was a password. If it had a password, then you would get an error when unwrapping the key.

**Comment by blonkm** [comment]
I got my files back! Thanks a lot. It really was this easy. Mounting with a loop device worked.
