### ISSUE TITLE
ASMedia chip

### ISSUE THREAD

**Issue by iTestAndroid** [andlabs/reallymine#75]
I have a new 8TB WD My Book. I opened it up and it does have asmedia asm1151w chip.

I tried to run `findkeyblock.sh` or a basic `dd` and it gives me `Input/Output error` where I can clearly see my 8TB disk in gparted (its password protected and I know the password, just want to see if I can recover key with reallymine)

When I run getdek:
`error running getdek: read /dev/sdd: input/output error`

Results for sg_raw c045:

> sg_raw -r 1k /dev/sdd c0 45 00 00 00 00 00 30
> SCSI Status: Good 
> 
> Received 17 bytes of data:
>  00     45 00 00 01 30 00 00 20  c8 08 3c 6e 00 00 00 01    E...0.. ..<n....
>  10     30                     
> 

If you have ideas for me or want to run some tests I'm ready to help in anyway. I also saw the "got HW crypto?" but they don't have anything for ASMedia chip.

Let me know if I can be of a help, also as I mentioned I have the password, so I can do all sorts of tests, even intrusive as I don't really have anything important in the drive. Looking forward to hearing from you

**Comment by themaddoctor** [comment]
ASAIK, they are not encrypted. I don't know how the password protection works. I think it blocks access only.

Did you do "getdek" on the drive while it was inside the original enclosure, or after you removed it and connected it some other way?

**Comment by iTestAndroid** [comment]
I just removed the top cover, its still in the enclosure. I can mount it in Linux using wd_tools, so its still working (with proper password). But As you can see in my comment above, I tried getdek and I get read /dev/sdd input/output error`

**Comment by themaddoctor** [comment]
That's because it's still in the WD enclosure. Anyway, I don't believe it has a DEK.

**Comment by iTestAndroid** [comment]
So if I get it out of enclosure, I should be able to get plain data?

**Comment by themaddoctor** [comment]
I think so.

**Comment by iTestAndroid** [comment]
Let me try and I'll report back real soon

**Comment by iTestAndroid** [comment]
Nope, it doesn't work, it doesn't mount, when I open gparted it keeps reporting IO error and I can't do dd.

**Comment by themaddoctor** [comment]
Then the lockout is on a chip on the disk's controller board.

**Comment by iTestAndroid** [comment]
What do you suggest as next step? What I can try?

**Comment by themaddoctor** [comment]
I don't know. What is your goal?

**Comment by iTestAndroid** [comment]
Try to see if I can get KEK or find the password etc and write code for reallymine to support ASMedia chips or if its on the disk, find out the chip and analyze it, just a challenge

**Comment by iTestAndroid** [comment]
sudo ./reallymine getdek /dev/sdd
error running getdek: read /dev/sdd: input/output error

Getting this on the 8TB HDD directly connected to my computer, no WD enclosure or SCSI/USB board

**Comment by themaddoctor** [comment]
put it back together and disable the password

**Comment by iTestAndroid** [comment]
and then? What's the next step?

**Comment by themaddoctor** [comment]
take it apart and try again

**Comment by iTestAndroid** [comment]
What do you mean? Please explain. I want to find a procedure/method where I can recover the key when I don't know it using reallymine

**Comment by themaddoctor** [comment]
ASAIK, they are not encrypted. I don't know how the password protection works. I think it blocks access only.

**Comment by iTestAndroid** [comment]
How can I put the theory in test? How I can try to access the data behind the password protection which you say is blocking access?

**Comment by themaddoctor** [comment]
put it back together and disable the password

**Comment by iTestAndroid** [comment]
Also FYI, when it was inside enclosure, the VID/PID was:
"1058:25ee"
now I connected it directly to my PC, its JMicron:
"152d:1561"

> put it back together and disable the password

I still don't get the idea behind it, what will I gain by disabling password? What can I do with that? What's the next step after disabling the password?

**Comment by iTestAndroid** [comment]
I'll wait for someone from reallymine project to respond. @andlabs

**Comment by themaddoctor** [comment]
You don't really hear what people are saying to you. So what difference does it make? You aren't willing to try disabling the password, so what does it matter what the "next step" is? Why are you trying to break the encryption on a drive that doesn't have encryption? I don't know. Your issues are not with the disk but with communication. Got HW Crypto? and ReallyMine don't deal with ASM chips, but you would know that if you were listening. You are banging your head against your own wall. Either disable the password and try again to access the bare drive, or don't. I no longer care and will not read any more of this thread. Good luck.

**Comment by iTestAndroid** [comment]
You don't listen at all, do you? I'm trying to find a way to recover the password. It returns 0x30 (FDE), we don't know if its encrypted or a simple chip blocking access. If I disable the password, how it will help? I want to recover password/disable password/protection when I don't have it.

**Comment by iTestAndroid** [comment]
@themaddoctor 
I'm not editing anything, maybe small things, but not trying to change the story. 
a) If its hardware block, is there any pointer on how to get rid of that/bypass that? I really don't care about this HDD even if I break it. I just want to see if I can do this and bypass the block.
b) I also researched and read, now also I have a feeling that ASM chip is not doing crypto (although some models have the capability), but what if the chip inside HDD is doing the crypto? How do you say with high confidence that its a "block", maybe something inside HDD controller board is doing crypto?

I need pointers and ideas, thats all, I already got couple more WD My Book to play and I opened them up and doing some tests. They all have ASM chip. So I want pointers/ideas on how to possibly I can bypass that "block" if its a block or crypto if its a crypto.
