### ISSUE TITLE
getdek over 20hours, continue ?

### ISSUE THREAD

**Issue by limitlessnine** [andlabs/reallymine#80]
Hello :)

I have a 5TB WD green drive that I salvaged from a dead usb enclosure (due to an unfortunate power spike from a cheap usb hub). The drive itself seems functional, but I haven't had any luck decrypting it. I couldn't determine the encryption chip vendor from the board number, 4061-705149-a00 rev.AD 

I have tried the following, 
A) themaddoctor's findkeyblock.sh on both /dev/sdb and /dev/sdb1, 
which did not find the keyblock

B) reallymine's getdek on /dev/sdb, it's been running for over 20 hours, atm I've paused the process with kill -STOP pid, and will resume if advised so

C) tried mounting them directly (hoping maybe dumb luck it isn't encrypted) with, 
mount -t ntfs /dev/sdb /mnt/5tb, and 
mount -t ntfs /dev/sdb1 /mnt/5tb,
both errors:
"The device '/dev/sdb' doesn't seem to have a valid NTFS."
"The device '/dev/sdb1' doesn't seem to have a valid NTFS."

the 5TB drive is definitely NTFS, it was used exclusively on my windows machine, and i recall it only showed up as one partition when it was running in the usb enclosure. I've kept the drive as is. I have not modified the partitions (oddly there's two of them showing under linux), the drive is directly connected via sata to the motherboard (not usb). 

I've enclosed the dumpfirst and dumplast for both sdb and sdb1, I would appreciate any advise you may have on how to proceed. Thank You

[sdb_dumplast.txt](https://github.com/andlabs/reallymine/files/2666924/sdb_dumplast.txt)
[sdb_dumpfirst.txt](https://github.com/andlabs/reallymine/files/2666925/sdb_dumpfirst.txt)
[sdb1_dumplast.txt](https://github.com/andlabs/reallymine/files/2666926/sdb1_dumplast.txt)
[sdb1_dumpfirst.txt](https://github.com/andlabs/reallymine/files/2666927/sdb1_dumpfirst.txt)

```
prompt: lsblk -o name,model,size,type
NAME            MODEL              SIZE TYPE
...
sdb             WDC WD50EZRX-00M   4.6T disk
└─sdb1                           582.2G part
...
```
```
prompt: sudo file -s /dev/sdb
/dev/sdb: DOS/MBR boot sector MS-MBR XP english at offset 0x12c "Invalid partition table" at offset 0x144 "Error loading operating system" at offset 0x163 "Missing operating system", disk signature 0x222f2; partition 1 : ID=0x7, start-CHS (0x0,4,5), end-CHS (0x3ff,254,63), startsector 256, 1220934144 sectors

prompt: sudo file -s /dev/sdb1
/dev/sdb1: data

```
```
prompt: sudo fdisk -l /dev/sdb
Disk /dev/sdb: 4.6 TiB, 5000947524096 bytes, 9767475633 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: dos
Disk identifier: 0x000222f2

Device     Boot Start        End    Sectors   Size Id Type
/dev/sdb1         256 1220934399 1220934144 582.2G  7 HPFS/NTFS/exFAT

```

**Comment by limitlessnine** [comment]
Hi themaddoctor, thanks for the prompt response.

I tried your suggestion, but it seems MBR's 2TB partition size limit restriction won't let me allocate last_sector past the range 2048-4294967294 offered by fdisk. Didn't save changes during the fdisk session.

Will attempt the following as time permits. Clone image drive and attempt recovery on the copy.
A) mount clone image, fdisk partition resize to max 2TB, see if i can recover half of the data
B) mount clone image, attempt MBR to GPT conversion, see if i can recover the remaining files
C) google
Z) last resort, ebay identical WD usb adapter board

Thanks for your guidance themaddoctor, its been a great help!


fdisk session:
```
prompt: sudo fdisk /dev/sdb

Welcome to fdisk (util-linux 2.32.1).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

The size of this disk is 4.6 TiB (5000947524096 bytes). DOS partition table format cannot be used on drives for volumes larger than 2199023255040 bytes for 512-byte sectors. Use GUID partition table format (GPT).

Command (m for help): p

Disk /dev/sdb: 4.6 TiB, 5000947524096 bytes, 9767475633 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: dos
Disk identifier: 0x000222f2

Device     Boot Start        End    Sectors   Size Id Type
/dev/sdb1         256 1220934399 1220934144 582.2G  7 HPFS/NTFS/exFAT

Command (m for help): d
Selected partition 1
Partition 1 has been deleted.

Command (m for help): p
Disk /dev/sdb: 4.6 TiB, 5000947524096 bytes, 9767475633 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: dos
Disk identifier: 0x000222f2

Command (m for help): n
Partition type
   p   primary (0 primary, 0 extended, 4 free)
   e   extended (container for logical partitions)
Select (default p): p
Partition number (1-4, default 1): 1
First sector (2048-4294967295, default 2048): 2048
Last sector, +sectors or +size{K,M,G,T,P} (2048-4294967294, default 4294967294): 9767475193
Value out of range.


prompt: sudo parted /dev/sdb print
	Model: ATA WDC WD50EZRX-00M (scsi)
	Disk /dev/sdb: 5001GB
	Sector size (logical/physical): 512B/4096B
	Partition Table: msdos
	Disk Flags: 

	Number  Start  End    Size   Type     File system  Flags
	 1      131kB  625GB  625GB  primary

```

**Comment by themaddoctor** [comment]
You could try cloning starting from sector 2048 (1MB from the start of the disk), and then mounting the clone as an unpartitioned drive with one filesystem on it. I do it all the time. Your NTFS filesystem starts at sector 2048. Remember to count from 0, not from 1.

**Comment by limitlessnine** [comment]
Thank You very much themaddoctor!

Your last tip was invaluable, once you hinted that it was possible to bypass the partition table, and mount the filesystem directly, I was able to mount the disk as is, saving a lot of time in the process.

mounting steps:
```
prompt: mount --version
	mount from util-linux 2.32.1 (libmount 2.32.1: selinux, btrfs, assert, debug)

prompt: sudo mount -t ntfs -o ro,offset=$((4096*2048)) /dev/sdb /mnt/5tb/
	NTFS signature is missing.
	Failed to mount '/dev/loop0': Invalid argument
	The device '/dev/loop0' doesn't seem to have a valid NTFS.
	Maybe the wrong device is used? Or the whole disk instead of a
	partition (e.g. /dev/sda, not /dev/sda1)? Or the other way around?

prompt: sudo mount -t ntfs -o ro,offset=$((512*2048)) /dev/sdb /mnt/5tb/

prompt: df -h /mnt/5tb
	Filesystem      Size  Used Avail Use% Mounted on
	/dev/loop0      4.6T  3.1T  1.6T  67% /mnt/5tb
```

closing ticket ^__^
