### ISSUE TITLE
Prepare the disk for decryption

### ISSUE THREAD

**Issue by Supermarco333** [andlabs/reallymine#86]
Hello,
My family has an old WD Passport (Essential probably) drive from 2011. (SN: WX70C8902692)
It's an USB2 board (the version of the board is 701675) and the Sata/USB chip is an Initio INIC-1607E. I'd like to perform a decryption because of course this drive was forgotten in a cupboard ann with time, nobody remember the password. When pluging in the drive with linux and running Gparted or reallymine, I get Input/Output errors. So, my question is: should I connect a SATA connector to the board (I don't want to buy the equivalent SATA board) like here: https://blog.acelaboratory.com/pc-3000-hdd-how-to-solder-a-sata-adapter-to-the-usb-western-digital-drive.html
Thank you very much for your answers.

**Comment by themaddoctor** [comment]
If you remove the original board, then you remove the keys and password with it. Then you won't be able to find the information you need to decrypt it.

**Comment by Supermarco333** [comment]
So ok I don't change the board, what shoud I do now, solder a sata port ?

**Comment by themaddoctor** [comment]
If you can find a guide that matches your board and are willing to take the risk of making a mistake. I've never done it before, so I'm no expert.

**Comment by themaddoctor** [comment]
I take back what I said earlier. The key is stored on the disk, but changing the board might not work due to other incompatibilities. Again, I am not an expert on Passports.

**Comment by Supermarco333** [comment]
Thanks to this article: https://blog.acelaboratory.com/pc-3000-hdd-how-to-solder-a-sata-adapter-to-the-usb-western-digital-drive.html
I know which capacitors to dissolder, and where to connect the sata port. I don’t want to buy another board (too expensive) even if I know the one that is compatible (thanks to the article). Do you think that it will solve the Input/Output errors with the sata port ? And I will be able to decrypt it without the password? If the disk is damaged, it’s not super super bad because as I said it’s an old disk, I just wanted to get back some photos that might be inside.

**Comment by themaddoctor** [comment]
I don't know about solving the errors.

To break the encryption I could do a dictionary attack if you can provide the keyblock from the disk and proof of ownership. The keyblock will be located near the end of the disk if you bypass the INIC chip.

**Comment by Supermarco333** [comment]
All right, if I succeed to solder a sata, dump the key sector, and find the invoice, I'll contact you back. Thanks for your answers.
