### ISSUE TITLE
Hashicorp moved ../helper/password to ../sdk/helper/password

### ISSUE THREAD

**Issue by fishbone68** [andlabs/reallymine#87]
Hi guys,

i just tried to compile reallymine and found out that HashiCorp moved the location of ../helper/password to ../sdk/helper/password. The commit was made 7 days ago:

https://github.com/hashicorp/vault/commit/a920c10be6e906001a235627483f92999166f4fc#diff-fde5d67bfb6dc4b598291cc2ce35ee4a

**Comment by andlabs** [comment]
I'm not using Hashicorp libraries...?

**Comment by fishbone68** [comment]
Maybe i‘m wrong but there is a reference to

import (
"fmt"
"os"
"encoding/hex"

"github.com/hashicorp/vault/helper/password"
)
in 

https://github.com/andlabs/reallymine/blob/master/kek/asker.go

**Comment by andlabs** [comment]
Yes, that's why I deleted the comment.

**Comment by hyllm** [comment]
i get error when installing reallymine with go...

`go get github.com/andlabs/reallymine
package github.com/hashicorp/vault/helper/password: cannot find package "github.com/hashicorp/vault/helper/password" in any of:
	/usr/lib/go-1.10/src/github.com/hashicorp/vault/helper/password (from $GOROOT)
	/home/michalik/go/src/github.com/hashicorp/vault/helper/password (from $GOPATH)`

**Comment by apassiou** [comment]
sooo... will **reallymine** source be changed to accommodate this? Otherwise its not compilable as is.

**Comment by andlabs** [comment]
Fixed.
