### ISSUE TITLE
Reallymine cannot be installed anymore

### ISSUE THREAD

**Issue by xterso** [andlabs/reallymine#98]
Hello,

I think reallymine cannot be installed anymore as it was meant to. Probably this is because hashicorp/vault was moved to somewhere else and because of that I get error when I try to install it. 

It was working some months before when I try to install it first time on another computer but now it is not possible anymore. 

Any solution?

**Comment by xterso** [comment]
Ok, I figured it out. Hashicorp moved github.com/hashicorp/vault/helper/password to github.com/hashicorp/vault/sdk/helper/password. So, install it manually first then copy ../vault/sdk/helper/password folder to ../vault/helper/password and run reallymine installation again. And voila! It works!

**Comment by andlabs** [comment]
Fixed.
